---
title: "MDS-EconAnalysis"
author: "Rock Chi"
date: "March 7, 2016"
output: html_document
---

```{r}
#Loading Required Libraries
library(Quandl)
library(dplyr)
library(ggplot2)
Quandl.api_key("ow7sStiu5X9dzfWKJGfz")
```


List of Least Developed Countries (LDC) - Updated February 16, 2016
- [http://www.un.org/en/development/desa/policy/cdp/ldc/ldc_list.pdf](http://www.un.org/en/development/desa/policy/cdp/ldc/ldc_list.pdf)

```{r}
#Creating a List of LDC Names and Inclusion Date from PDF, updated Feb 16, 2016
#Congo and Congo-Brazzaville: Congo was used as Congo refers in link to Dem. Republic of Congo which is the one within UN List
#GDP data from Somalia is missing. So, Somalia is taken out of LDC Countries list
LDCName <- c("Afghanistan", "Angola", "Bangladesh", "Benin", "Bhutan", "Burkina Faso", "Burundi", "Cambodia", "Central African Republic", "Chad", "Comoros", "Congo", "Djibouti", "Equatorial Guinea", "Eritrea", "Ethiopia", "Gambia", "Guinea", "Guinea-Bissau", "Haiti", "Kiribati", "Laos", "Lesotho", "Liberia", "Madagascar", "Malawi", "Mali", "Mauritania", "Mozambique", "Myanmar", "Nepal", "Niger", "Rwanda", "Sao Tome and Principe", "Senegal", "Sierra Leone", "Solomon Islands", "South Sudan", "Sudan", "Timor-Leste", "Togo", "Tuvalu", "Uganda", "Tanzania", "Vanuatu", "Yemen", "Zambia")
IncDate <- c(1971, 1994, 1975, 1971, 1971, 1971, 1971, 1991, 1975, 1971, 1977, 1991, 1982, 1982, 1994, 1971, 1975, 1971, 1981, 1971, 1986, 1971, 1971, 1990, 1991, 1971, 1971, 1986, 1988, 1987, 1971, 1971, 1971, 1982, 2000, 1982, 1991, 2012, 1971, 2003, 1982, 1986, 1971, 1971, 1985, 1971, 1991 )
CountryCode <- c("AFG", "AGO", "BDG", "BEN", "BTN", "BFA", "BDI", "KHM", "CAF", "TCD", "COM", "COD", "DJI", "GNQ", "ERI", "ETH", "GMB", "GIN", "GNB", "HTI", "KIR", "LAO", "LSO", "LBR", "MDG", "MWI", "MLI", "MRT", "MOZ", "MMR", "NPL", "NER", "RWA", "STP", "SEN", "SLE", "SLB", "SSD", "SDN", "TLS", "TGO", "TUV", "UGA", "TZA", "VUT", "YEM", "ZMB")
LDC <- cbind(LDCName, IncDate,Code)
rm(LDCName, IncDate)
```



```{r}
#Function to Programmatically Grab Timeseries Dataset and Merge into one Table
#codename is an array of CountryCodes, QDLName is the code for Quandl dataset
grabData <- function(codename, QDLName){
  temptable <- c()
  for (i in seq(codename)){
    fullcode <- paste("ODA/", codename[i], "_", QDLName, sep="")
    subquery <- Quandl(fullcode, end_date="2015-12-31", collapse="annual")
    subquery$CountryCode <- codename
    temptable <- rbind(temptable, subquery)
    }
  temptable
}
```
